# Generated by Django 5.0 on 2023-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel/image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
