# Generated by Django 5.0 on 2023-12-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_images',
            field=models.ImageField(upload_to='hotel/hotel_images/'),
        ),
    ]
