# Generated by Django 5.0 on 2023-12-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
    ]
