# Generated by Django 5.0 on 2023-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_slug_alter_hotel_address_alter_hotel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, to='hotel.image'),
        ),
    ]
